pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "mithunsd27/social-app"
        DOCKER_TAG = "latest"
        DOCKER_CREDENTIALS_ID = "Dockerhub"
        GITHUB_CREDENTIALS_ID = "Git"
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: GITHUB_CREDENTIALS_ID, url: 'https://github.com/sdmithun2701/Devopstask5', branch: 'main'
            }
        }

        stage('Build Application') {
            steps {
                script {
                    sh '${MAVEN_HOME}/bin/mvn clean package -DskipTests'
                }
            }
        }

        stage('Run Maven Tests') {
            steps {
                script {
                    try {
                        sh 'mvn test'
                    } catch (Exception e) {
                        echo "Tests failed, but proceeding..."
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: DOCKER_CREDENTIALS_ID, url: '']) {
                    sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }

        // stage('Deploy to Kubernetes') {
        //     steps {
        //         script {
        //             sh '''
        //                 chmod +x scripts/deploy.sh
        //                 ./scripts/deploy.sh
        //             '''
        //         }
        //     }
        // }
    }

    post {
        success {
            echo "Deployment Successful!"
        }
        failure {
            echo "Deployment Failed!"
        }
    }
}
